name: Library Seat Crawler

on:
  schedule:
    # UTC 기준 21~23 → KST 06~08
    - cron: "0,30 21-23 * * *"
    # UTC 기준 0~14 → KST 09~23:30
    - cron: "0,30 0-14 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: library-seat-crawler
  cancel-in-progress: true

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run crawler
        run: python crawler.py

      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git remote set-url origin https://$GH_PAT@github.com/${{ github.repository }}.git
          git fetch origin main || true
          git pull --rebase origin main || true
          git add library_seats.csv
          git commit -m "Update data: $(date)" || echo "No changes"
          git push origin HEAD:main || true
